"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useState } from "react";
import { useRouter } from "next/navigation";
const schema = z.object({ repoUrl: z.string().url("Enter a valid URL").startsWith("https://", "URL must use HTTPS"), liveUrl: z.string().url("Enter a valid URL").startsWith("https://", "URL must use HTTPS") });
type FormValues = z.infer<typeof schema>;
export default function SubmissionForm({ projectId, initialRepoUrl = "", initialLiveUrl = "" }: { projectId: string; initialRepoUrl?: string; initialLiveUrl?: string }) { const router = useRouter(); const [serverError, setServerError] = useState(""); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { repoUrl: initialRepoUrl, liveUrl: initialLiveUrl } }); async function submit(values: FormValues) { setServerError(""); const response = await fetch("/api/submissions/create", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, ...values }) }); const result: { error?: string } = await response.json(); if (!response.ok) { setServerError(result.error ?? "Unable to submit"); return; } router.refresh(); } return <form onSubmit={handleSubmit(submit)} className="space-y-4 rounded-2xl border border-white/10 bg-white/[0.04] p-6"><div><label htmlFor="repoUrl" className="text-sm text-zinc-300">GitHub Repository URL</label><input id="repoUrl" {...register("repoUrl")} placeholder="https://github.com/username/project" className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-white outline-none focus:border-cyan-400" />{errors.repoUrl && <p className="mt-1 text-sm text-rose-300">{errors.repoUrl.message}</p>}</div><div><label htmlFor="liveUrl" className="text-sm text-zinc-300">Live Project URL</label><input id="liveUrl" {...register("liveUrl")} placeholder="https://your-project.com" className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-white outline-none focus:border-cyan-400" />{errors.liveUrl && <p className="mt-1 text-sm text-rose-300">{errors.liveUrl.message}</p>}</div>{serverError && <p role="alert" className="text-sm text-rose-300">{serverError}</p>}<button disabled={isSubmitting} className="rounded-lg bg-cyan-500 px-4 py-2 font-medium text-slate-950 disabled:opacity-60">{isSubmitting ? "Submitting..." : "Submit project"}</button></form>; }
