import ShareCertificateButton from "@/components/certificate/ShareCertificateButton";
import Link from "next/link";
import { redirect } from "next/navigation";
import { getUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { getCertificateData } from "@/lib/certificateData";

export default async function CertificatesPage() {
  const user = await getUser();
  if (!user) redirect("/auth/signin");
  const supabase = await createClient();
  const { data: certificates } = await supabase.from("certificates").select("verification_code").eq("user_id", user.id).order("issued_at", { ascending: false });
  const data = (await Promise.all((certificates ?? []).map((certificate) => getCertificateData(supabase, certificate.verification_code, user.id)))).filter(Boolean);
  return <main className="zi-container zi-page"><header className="zi-page-heading"><div><p className="zi-eyebrow">Your achievements</p><h1>Your certificates</h1><p>Verified proof of the projects you have completed.</p></div></header>{data.length ? <div className="zi-stack">{data.map(certificate=>certificate && <article className="zi-panel" key={certificate.id}><div className="zi-detail-grid"><div><div className="zi-certificate-preview"><span className={`zi-badge ${certificate.integrityValid && certificate.status === "verified" ? "approved" : "pending"}`}>{certificate.integrityValid ? certificate.status : "Integrity check failed"}</span><p className="zi-eyebrow">ZeroIntern / Certificate of achievement</p><h2>{certificate.trackName}</h2><p>Awarded to</p><h3>{certificate.studentName}</h3><p>{certificate.projects.length} approved projects</p></div><p className="zi-caption mt-3">Summary preview. Open the PDF for the issued certificate.</p></div><div className="zi-stack"><a href={`/api/certificates/download?code=${encodeURIComponent(certificate.verificationCode)}`} className="zi-btn zi-btn-primary">Download certificate</a><a href={`/api/certificates/download?code=${encodeURIComponent(certificate.verificationCode)}&preview=true`} target="_blank" rel="noreferrer" className="zi-btn zi-btn-secondary">Preview PDF</a><ShareCertificateButton code={certificate.verificationCode} /><div className="zi-verification-box"><h3>Credential ID</h3><code>{certificate.verificationCode}</code><Link href={`/certificate/verify/${encodeURIComponent(certificate.verificationCode)}`} className="zi-back-link">Verify credential &rarr;</Link></div></div></div><dl className="zi-certificate-details"><div><dt>Track completed</dt><dd>{certificate.trackName}</dd></div><div><dt>Issued date</dt><dd>{new Date(certificate.issuedAt).toLocaleDateString("en-US")}</dd></div><div><dt>Projects approved</dt><dd>{certificate.projects.length}</dd></div><div><dt>Credential type</dt><dd>Project achievement</dd></div></dl></article>)}</div> : <div className="zi-panel"><h2>Your work will go here</h2><p>Receive approval for every project in a track to earn your certificate.</p><Link href="/dashboard" className="zi-btn zi-btn-primary">Continue learning</Link></div>}</main>;
}
